---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/ukabu/pcf-attendee-service-code
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: api.run-01.haas-66.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service
    trigger: true
  - task: test
    file: attendee-service/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: attendee-service-unrebutted-fulguration.cfapps-01.haas-66.pez.pivotal.io
